# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
language: de
title: Lerne Deutsch mit uns
author:
  email: venera.urgazieva@protonmail.com
description: Vorbereitung für die ÖIF Prüfung
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lernedeutsch.org" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
minima:
  skin: solarized-dark

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include:
 - _pages
 - .htaccess
 - _files_a1_schreiben
 - _files_a1_grammatik
 - _files_a1_lesen
 - _files_a1_sprechen
 - _files_a1_pruefung
 - _files_b1_schreiben
 - _files_b1_grammatik
 - _files_b1_lesen
 - _files_b1_sprechen
 - _files_b1_pruefung